### ISSUE TITLE
C++ version?

### ISSUE THREAD

**Issue by laoshaw** [ultimatepp/ultimatepp#115]
Just found out U++ today, I wonder which c++ version I can use with it? also, can I make a static build on windows(e.g. users do not need install mingw etc before they can run the app)

**Comment by klugier** [comment]
Hello Laoshaw,

Glad that you found our project! U++ source code is currently written in C++14, however it is compatible with C++20. It means that apps written in our framework can be C++20.  In the context of static builds we support them on windows by default. It means that once you compile your app, you can move it to other computer and run it without the need of copying anything else.

If you have questions, I invite you to join our forum on https://www.ultimatepp.org/forums/. We have big community eager to help people like You. You can also check our rich [tutorials](https://www.ultimatepp.org/www$uppweb$Tutorials$en-us.html).

Does it solve your concerns? 

Klugier

**Comment by laoshaw** [comment]
yes thanks! just built some examples on windows and linux, looks cool. will keep learning.

**Comment by klugier** [comment]
If you found any problems please let us know. Thanks!  I am closing this issue...
