### ISSUE TITLE
On Windows (Clang x64) FileSel returns all paths without path seperators

### ISSUE THREAD

**Issue by niansa** [ultimatepp/ultimatepp#134]
Here is simple test code:

    FileSel fileSel;
    fileSel.Multi(false)
           .Type("Executable", "*.exe")
           .AllFilesType()
           .DefaultExt("exe")
           .ExecuteOpen("Select executable");
    ErrorOK(static_cast<const char*>(~fileSel));

![image](https://user-images.githubusercontent.com/20720267/212296020-87e17600-be24-48e3-ba1c-99dea26e0e10.png)

**Comment by niansa** [comment]
Turns out you need to DeQtf these strings...

**Comment by mirek-fidler** [comment]
Just a note: "\1" is an equivalent of DeQtf, till the next "\1". Usually
easier to use.
