### ISSUE TITLE
SysInfo: SimulateActivity class breaks compile with POSIX & NO_XTEST

### ISSUE THREAD

**Issue by erikjwaxx** [ultimatepp/ultimatepp#14]
`SysInfo::SimulateActivity` introduces an _unconditional_ dependency on `Keyb_SendKeys`.

However, this function is _conditionally_ defined based on `#if defined(PLATFORM_WIN32) || !defined(flagNO_XTEST)`.

**Comment by izabala123** [comment]
Solved, thank you for the report.
