### ISSUE TITLE
This is wonderful

### ISSUE THREAD

**Issue by dddomodossola** [ultimatepp/ultimatepp#145]
Please excuse me if I open an issue for this. But I want to share that, in my opinion, U++ is one of the most wonderful C++ tools!
Thank you very much for the great work. 
Feel free to close this issue when you want.

**Comment by mirek-fidler** [comment]
Well, spread the word :)

Thanks.

**Comment by klugier** [comment]
Hello,

Thanks for good words! If you want to talk more I encourage you to join our forum and Discord server. BTW, I wish we have more issues like this one ;)

Also, I agree with Mirek with spread the word! Any help are welcome, such as creation of technical articles about our framework in English or your native language.

Klugier

**Comment by dddomodossola** [comment]
Thank you a lot for the invitation to the forum and Discord, I will join.
And sure I will promote the use of U++!
