### ISSUE TITLE
[TheIDE] Functions possibly returning the address of a local variable. [-Wreturn-local-addr]

### ISSUE THREAD

**Issue by ismail-yilmaz** [ultimatepp/ultimatepp#15]
OS: Linux   (5.5.7)
UI: Gnome (3.34)
Compiler:  GCC (9.2.1)

GCC complains about two related functions possibly returning the address of a local variable.

https://github.com/ultimatepp/ultimatepp/blob/1b555b5385b12de7e325f13285aa866e6cf93016/uppsrc/ide/Browser/CodeBrowser.cpp#L237

And

https://github.com/ultimatepp/ultimatepp/blob/1b555b5385b12de7e325f13285aa866e6cf93016/uppsrc/ide/Browser/CodeBrowser.cpp#L242

**Comment by mirek-fidler** [comment]
This really seems border (for some specific Value, it would be true, but not those returned by Get(i, 1), however code does not know that...), but fix costs a little, so please test with current trunk/head.

**Comment by ismail-yilmaz** [comment]
Thank you.
Compiler warning is gone, and TheIDE compiles without any problem or warning.
