### ISSUE TITLE
Alt+Tab switches window when creating new package causing desktop to fallback mode under Linux Mint 21.2

### ISSUE THREAD

**Issue by erusyd** [ultimatepp/ultimatepp#157]
![Peek 2023-07-22 07-01](https://github.com/ultimatepp/ultimatepp/assets/1529102/806ec56e-d6ef-4729-a7b1-06f4b933e0e6)

**Comment by klugier** [comment]
Hello [erusyd](https://github.com/erusyd),

Why do not raise the same issue to Linux Mint? We do not do anything special here and if client app can crash DE. It means that it is not secure enough and it can not protect itself and users from malicious application. I am personally using KDE and didn't notice that issue with RADEON kernel driver.

I also tested with GNOME 32.0 on VirtualBox and I can not reproduce the problem.

It might be also issue with your hardware not DE issue itself. What is your computer specification? Did you als install any unstable packages? How TheIDE behaves once you create package and click ALT+TAB?

**Comment by erusyd** [comment]
I have nvidia driver 525.125.06 installed for GeForce 940MX. I also switched to 535.54.03 and Intel internal gpu dirver. The problem still arises.
Maybe it is the problem of Linux Mint. I recently upgrade Linux Mint 21.1 to 21.2. I'll try to raise the issue to Linux Mint.

**Comment by klugier** [comment]
One more question - are you using Wayland desktop session?

**Comment by erusyd** [comment]
I use x11 desktop session:
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/e4101b87-768f-4ee0-86f5-d3f0cd04dabd)

Btw, I find that TheIDE won't trigger this problem, only when I click "New package" in "Select main package" window and continuously fast switching using ALT+TAB will trigger fallback.

**Comment by erusyd** [comment]
I tested U++ under windows 10 and manjaro-xfce inside virtualbox, no such problem. So maybe it's really the problem of Linux Mint Cinnamon.

**Comment by erusyd** [comment]
I attached the .xsession-errors, hope if has any insight.
[xsession-errors.zip](https://github.com/ultimatepp/ultimatepp/files/12157960/xsession-errors.zip)

**Comment by mirek-fidler** [comment]
Any chance you are running e.g. chinesse input method? (Some indication in xsession-errors points to that).

Also, does it crash on Ctrl-Tab of New package dialog only, or with other windows / dialogs too?

If other too, does UWord (example) crash too with Ctrl-Tab?

**Comment by erusyd** [comment]
The .xsession-errors is misleading. Triggering fallback not necessarily generates .xsession-errors file.
I recorder a gif to show the whole process: (1) start TheIDE and open an example, then continuously fast switching window by Alt+Tab won't trigger fallback (2) "File"->"Open main package", then continuously fast switching window won't trigger fallback (2) Click "New package",  then continuously fast switching window using Alt+Tab after many times trigger fallback
![Peek 2023-07-26 10-11](https://github.com/ultimatepp/ultimatepp/assets/1529102/7df8e0d0-0679-4a3b-a3c1-c33e864932b2)
So maybe "New package" window hits Mint Cinnamon's weak point.
