### ISSUE TITLE
How to let TheIDE use higher version clang/gcc to parse C++ code in std=c++17/20

### ISSUE THREAD

**Issue by erusyd** [ultimatepp/ultimatepp#158]
I have codes using C++17/20 libraries and TheIDE parsing shows errors:
![scoped_lock](https://github.com/ultimatepp/ultimatepp/assets/1529102/bb40a49f-1682-47b6-8205-851b55379ce3)
![optional](https://github.com/ultimatepp/ultimatepp/assets/1529102/01d9a0e3-dd8c-4a3b-9ead-7bf1a6fcf602)
![atomic](https://github.com/ultimatepp/ultimatepp/assets/1529102/8a64dc25-ff5e-41a9-a325-9bd69ae82944)
![format](https://github.com/ultimatepp/ultimatepp/assets/1529102/cb891aa9-dbd2-434f-b58c-d63c70623ac8)
I guess it's because TheIDE parsing uses c++14 standard. So how to let TheIDE use higher version clang/gcc with C++17/20 standards. I have gcc-13 installed via linuxbrew and clang-16 installed via ubuntu ppa.

![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/6c41f1a3-5663-456a-a3e0-7246cde57ac1)

**Comment by mirek-fidler** [comment]
Settings/Assist, bottom of window there are additional libclang commandline
parameters.

Adding "-std=c++17" there should help. (Please confirm).

Mirek

**Comment by erusyd** [comment]
Adding "-std=c++20" makes first three parsing errors gone, but "std::format" parsing error still exists. Maybe it's because the default libclang is 14? How to change TheIDE to use higher version clang?

**Comment by erusyd** [comment]
I changed My Emacs' lsp clangd from version 16 to version 14 and the syntax parsing of "std::format" is still OK:
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/1ea7f911-15d6-4ceb-bd05-88b9169588ec)
So maybe TheIDE can do something like lsp with compile_commands.json.

**Comment by erusyd** [comment]
I see TheIDE clang parser uses "/usr/include/c++/11/" as default path:
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/46fc2131-f74c-429f-a9fe-261d2fa50edd)

So is it possible to add include path to gcc-13 in the following location?
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/f5a0d534-6980-472a-ae04-3beffa171ae1)

**Comment by erusyd** [comment]
I successfully compiled my application with GCC builder with following settings:
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/393a2ab6-0b8f-42ed-b595-d4d16ec72d6d)

But the parser begins to show a lot of errors:
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/ce2f49ed-8668-493f-8f35-6cb3c49ecb56)

What I suppose is that TheIDE libclang parser should work independently from builder mode selection.

**Comment by mirek-fidler** [comment]
Have you tried adding the correct path with -I in additional compiler
options?

(I will probably make all this experience smoother soon by providing C++
version selection in Assist dialog, but would be nice to know what
parameters to add there).

Mirek

**Comment by erusyd** [comment]
I have tried this (even multiple -I{path}) and doesn't work:
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/4e7010ab-940b-4358-98b7-d3f0edf5db5f)

**Comment by erusyd** [comment]
Through my current exercises, commons ones are:
-Wall, -std=c++17/20, -fmodules-ts, `pkg-config --cflags --libs xxx`

**Comment by mirek-fidler** [comment]
What is this? Working commandline or what?

**Comment by erusyd** [comment]
These are just some gcc compile options in my makefile and use "bear -- make" to generate compile_commands.json.
For example, "pkg-config --cflags --libs gtkmm-4.0" will generate gtkmm related header and lib path.

**Comment by mirek-fidler** [comment]
Please try to build the latest theide - I have added C++ standard selection
in the assist setup. Seems to work for me... (but I will be glad if you
confirm).

Mirek

**Comment by erusyd** [comment]
Yes, It works for me. Thanks!
