### ISSUE TITLE
TheIDE windows version shows parsing errors

### ISSUE THREAD

**Issue by erusyd** [ultimatepp/ultimatepp#162]
I downloaded Protect package from:
https://www.ultimatepp.org/forums/index.php?t=rview&th=5547&goto=49922
When I open "ProtectEncrypt" from linux, parsing is OK:
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/d60f1e72-dcc1-4f2a-93ae-f17f77d040f3)
But when I open it from Windows 10 Enterprise LTSC in vmware workstation, it shows parsing errors:
![image](https://github.com/ultimatepp/ultimatepp/assets/1529102/43c44140-604f-4fa7-b75b-341d06268a06)

I've attached the source files(put "Protect" and "Xed" in uppsrc, and "ProctecEncrypt" in MyApps):
[ProtectPackage.zip](https://github.com/ultimatepp/ultimatepp/files/12460929/ProtectPackage.zip)

**Comment by mirek-fidler** [comment]
This might be fixed in the current master, please check.

**Comment by erusyd** [comment]
Problem still exists:
![xxx](https://github.com/ultimatepp/ultimatepp/assets/1529102/e771f15e-948c-410d-bbb5-154f06042e81)

**Comment by mirek-fidler** [comment]
If you activate Assist diagnostics in Settings/Assist, there should be
"Current file parse errors" in Assist menu. Can you dump that list here?

Also, looking at the screenshot, it feels like it is possibly actual error.
If it is not "private" code, can you send me "ProtectEncrypt"?

**Comment by erusyd** [comment]
Everything is in the zip. Put "Protect" and "Xed" in uppsrc, and "ProctecEncrypt" in MyApps:
[ProtectPackage.zip](https://github.com/ultimatepp/ultimatepp/files/12460929/ProtectPackage.zip)

**Comment by erusyd** [comment]
[parse_errors.txt](https://github.com/ultimatepp/ultimatepp/files/12536197/parse_errors.txt)

**Comment by mirek-fidler** [comment]
Well, it does not build either. The problem is in Xed - VERSION file
conflicts with standard library version file. Renaming VERSION to VERSION0
fixes both build and Assist.

**Comment by erusyd** [comment]
Thanks. MSVC17 compiler is OK with VERSION file. I'm just wondering why Linux does not have such problem.

**Comment by mirek-fidler** [comment]
Linux: "VERSION" vs "version" I think - win32 is case insensitive.

All that said, maybe assist handling of internal includes is not quite
correct - I put that dir at the end of include path...

Mirek

**Comment by erusyd** [comment]
OK, clear now.
