### ISSUE TITLE
Calendar control localization format

### ISSUE THREAD

**Issue by zeroonestring** [ultimatepp/ultimatepp#198]
![微信图片_20240429092011](https://github.com/ultimatepp/ultimatepp/assets/16793041/530efd7b-d824-47fe-bb86-f4f2a96b4df9)

The interface displays the English format, I want to let the Chinese format be displayed.

**Comment by klugier** [comment]
Solved on the forum https://www.ultimatepp.org/forums/index.php?t=msg&goto=60556&#msg_60556.
