### ISSUE TITLE
Extend the number of supported platforms

### ISSUE THREAD

**Issue by ghost** [ultimatepp/ultimatepp#20]
This will be without much efforts. Your code to some extent is already portable. I have tried to compile it on many platforms and most of the time the compilation success without any errors but the real show stopper is the linking part, because you assumed too much Linux specific. For example: Upp compiled cleanly on NetBSD but fails at the linking stage since it's looking for -ldl and there is no such thing on NetBSD. The same would apply for OpenBSD.

Please let me know if you are going to support more platforms or just stick to the combo Win + Lin + Mac, thank you.

**Comment by CoolmanCZ** [comment]
Hi,

Send the request to the [Ultimatepp forum](https://www.ultimatepp.org/forums/). This Github repository is the mirror only.

BR, Radek
