### ISSUE TITLE
assigning to 'char *' from 'unsigned char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not

### ISSUE THREAD

**Issue by ghost** [ultimatepp/ultimatepp#203]
when installing with the install script:

![image](https://github.com/user-attachments/assets/9e665a01-fe32-478c-a470-ca2e991c1ba0)

**Comment by mirek-fidler** [comment]
Yeah, that happens when Freetype maintainers decide to change the API for no good reason. It should be already fixed in master head (and nightly builds).

**Comment by ghost** [comment]
yes, it's fixed. should i keep this open until release, or close it now?

**Comment by mirek-fidler** [comment]
Well, I guess if this is TODO list, then until we some finer status resolution, I am closing this...
