### ISSUE TITLE
UppHub problem when TheIDE is installed under a folder with spaces

### ISSUE THREAD

**Issue by izabala123** [ultimatepp/ultimatepp#208]
Now UppHub fails to run git clone if the folder where TheIDE is installed has spaces.

This can be solved by replacing in file ide/UppHub.cpp, line 555

`cmd << ' ' << dir;`

with 

`cmd << " \"" << dir << "\"";`

![image](https://github.com/user-attachments/assets/c519a5af-6af7-40f6-9539-06e05bccb861)

Best regards
Iñaki

**Comment by mirek-fidler** [comment]
Thanks!

**Comment by izabala123** [comment]
You're welcome!
