### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [ultimatepp/ultimatepp#26]

**Comment by klugier** [comment]
@graysuit why do you want to have as smallest executable as possible. Do you want to save executable on the floppy (1 mb)? In the past we had option to optimize executable by size, but until now nobody raised the concern about this issue. However, our optimization was not such significant as you expected.

There is an option in the "Output mode". You need to click on the compiler name like "GCC Debug" or "Clang Debug" (or release if you selected to build release). Then you can select "All shared" for the build you have. It will produced shared library and your executable will be minimal. Mine for GUI example is around 0.15 Mb. However, you still need to deliver these libraries....

**Comment by graysuit** [comment]
> @graysuit why do you want to have as smallest executable as possible. Do you want to save executable on the floppy (1 mb)? In the past we had option to optimize executable by size,

lol floppy xD, its was so old time when we use floppies. 
The reason behind lower down file size as much as possible because
In our country, named **pakistan** have slow internet connections. Even in developed capital **islamabad**, net speed is around 300kb--500kb's per second. And other region have much more slower connections.
My project is big so I assume it would become more than 50 mb's.

> but until now nobody raised the concern about this issue. 

May be mostly your users are Europeans. And they have well electronic facilities which Asians don't have.

> There is an option in the "Output mode". You need to click on the compiler name like "GCC Debug" or "Clang Debug" (or release if you selected to build release). Then you can select "All shared" for the build you have. It will produced shared library and your executable will be minimal. Mine for GUI example is around 0.15 Mb. However, you still need to deliver these libraries....

I am using Visual C++ . When I check **shared libs** it compiles fine and results 1.33 mb.
But when I try to compile with **all shared libs**, it show errors, Please see:
```
----- plugin/z ( GUI MSC17 SO SHARED MSC WIN32 ) (1 / 10)
adler32.c
compress.c
crc32.c
infback.c
deflate.c
inflate.c
inffast.c
inftrees.c
uncompr.c
trees.c
zutil.c
Creating library...
plugin/z: 11 file(s) built in (0:05.13), 467 msecs / file, duration = 5137 msecs
   Creating library D:\upp\upp\out\examples\MSVS17.Gui.Shared.So\plugin_z.lib and object D:\upp
    \upp\out\examples\MSVS17.Gui.Shared.So\plugin_z.exp
D:\upp\upp\out\examples\MSVS17.Gui.Shared.So\plugin_z.dll (36352 B) created in (0:02.98)
----- Core ( GUI MSC17 SO SHARED MSC WIN32 ) (2 / 10)
PCH: Core.h
Core.h
Cpu.cpp
Mt.cpp
heaputil.cpp
hheap.cpp
sheap.cpp
lheap.cpp
heap.cpp
heapdbg.cpp
StringFind.cpp
String.cpp
WString.cpp
StrUtil.cpp
Utf.cpp
SplitMerge.cpp
UnicodeInfo.cpp
CharSet.cpp
Bom.cpp
NetNode.cpp
App.cpp
Path.cpp
Huge.cpp
Stream.cpp
BlockStream.cpp
FileMapping.cpp
FilterStream.cpp
Log.cpp
Debug.cpp
Util.cpp
Ini.cpp
mathutil.cpp
Random.cpp
Speller.cpp
LocalProcess.cpp
Vcont.cpp
TimeDate.cpp
Index.cpp
ValueUtil.cpp
Value.cpp
Convert.cpp
Color.cpp
Format.cpp
Gtypes.cpp
Lang.cpp
LangInfo.cpp
t.cpp
parser.cpp
Xmlize.cpp
XML.cpp
Uuid.cpp
JSON.cpp
Ptr.cpp
z.cpp
Topic.cpp
CoWork.cpp
MD5.cpp
lz4.c
SHA256.cpp
xxhash.c
SHA1.cpp
xxHsh.cpp
MIME.cpp
InetUtil.cpp
Socket.cpp
WebSocket.cpp
Dli.cpp
Http.cpp
Win32Util.cpp
Creating library...
Core: 68 file(s) built in (0:41.14), 605 msecs / file, duration = 41149 msecs
   Creating library D:\upp\upp\out\examples\MSVS17.Gui.Shared.So\Core.lib and object D:\upp\upp
    \out\examples\MSVS17.Gui.Shared.So\Core.exp
z.obj : error LNK2019: unresolved external symbol _deflate referenced in function "private: voi
    d __thiscall Upp::Zlib::Pump(bool)" (?Pump@Zlib@Upp@@AAEX_N@Z)
z.obj : error LNK2019: unresolved external symbol _deflateEnd referenced in function "private: 
    void __thiscall Upp::Zlib::Free(void)" (?Free@Zlib@Upp@@AAEXXZ)
z.obj : error LNK2019: unresolved external symbol _inflate referenced in function "private: voi
    d __thiscall Upp::Zlib::Pump(bool)" (?Pump@Zlib@Upp@@AAEX_N@Z)
z.obj : error LNK2019: unresolved external symbol _inflateEnd referenced in function "private: 
    void __thiscall Upp::Zlib::Free(void)" (?Free@Zlib@Upp@@AAEXXZ)
z.obj : error LNK2019: unresolved external symbol _crc32 referenced in function "public: __this
    call Upp::Crc32Stream::Crc32Stream(void)" (??0Crc32Stream@Upp@@QAE@XZ)
z.obj : error LNK2019: unresolved external symbol _deflateInit2_ referenced in function "public
    : void __thiscall Upp::Zlib::Compress(void)" (?Compress@Zlib@Upp@@QAEXXZ)
z.obj : error LNK2019: unresolved external symbol _inflateInit2_ referenced in function "public
    : void __thiscall Upp::Zlib::Decompress(void)" (?Decompress@Zlib@Upp@@QAEXXZ)
D:\upp\upp\out\examples\MSVS17.Gui.Shared.So\Core.dll : fatal error LNK1120: 7 unresolved exter
    nals

There were errors. (0:49.61)

```
