### ISSUE TITLE
The tutorial Gui14 on ubuntu 18.04 doesn't have buttons well sized

### ISSUE THREAD

**Issue by mingodad** [ultimatepp/ultimatepp#29]
When building the project for the tutorial Gui14 on ubuntu 18.04 the buttons do not have proper sizes see attached screenshot.

![gui14](https://user-images.githubusercontent.com/462618/103639954-79d5d680-4f4f-11eb-8c5e-b09f165d7835.png)

**Comment by klugier** [comment]
What do you mean by "not have proper" size? It looks very similar to the reference image https://www.ultimatepp.org/srcdoc$CtrlLib$Tutorial_en-us.html#14. Also, the smaller buttons are intentional, because they show when auto scaling is disable (h and v prefix).

@mingodad

**Comment by mingodad** [comment]
Well it doesn't look like the tutorial pictures, the width of "hcenter-bottom" is croping the text and height is too just (again nothing like the tutorial picture).

**Comment by mingodad** [comment]
Also I think that's a good idea to revise the GUI Tutorial because some examples give a bad image for the hard work done on Ultimate++ framework, see attached example of Gui20c on ubuntu 18.04.

![gui20c](https://user-images.githubusercontent.com/462618/103664823-fa59fe80-4f72-11eb-8af8-1db7b919c7b2.png)

**Comment by klugier** [comment]
Can you post the screen resolution you have? Is this UHD display? On my machine this example looks good.

**Comment by ismail-yilmaz** [comment]
@klugier 
> Can you post the screen resolution you have? Is this UHD display? On my machine this example looks good.

`Gui20c` doesn't look good on 1080p either.

Let's try this better anchored one for Gui20c?

```
#include <CtrlLib/CtrlLib.h>

using namespace Upp;

struct MyAppWindow : TopWindow {
	Button ok, cancel;
	EditDate date;

	MyAppWindow() {
		SetRect(0, 0, 320, 90);
		Add(date.HSizePosZ(4, 4).TopPosZ(10, 24));
		Add(ok.SetLabel("OK").LeftPosZ(4, 64).BottomPosZ(4, 24));
		Add(cancel.SetLabel("Cancel").RightPosZ(4, 64).BottomPosZ(4, 24));

		ok.Ok() << Acceptor(IDOK);
		cancel.Cancel() << Rejector(IDCANCEL);
	}
};

GUI_APP_MAIN
{
	MyAppWindow app;
	switch(app.Run()) {
	case IDOK:
		PromptOK(String().Cat() << "OK: " << ~app.date);
		break;
	case IDCANCEL:
		Exclamation("Canceled");
	}
}
```

**Comment by mingodad** [comment]
My screen resolution is 1920x1080, the Gui20c proposed by Ismail looks reasonable.

**Comment by mirek-fidler** [comment]
First of all, thank you for you contributions, definitely appreciated.

I have gone through the tutorial, hopefully all should be now fixed.

**Comment by mingodad** [comment]
Looking through the commit https://github.com/ultimatepp/ultimatepp/commit/082cd6a3390ca873ab6f169ca532172a27e1664d I can see that several small changes where done, meaning that a review was indeed needed.

Thank you !

**Comment by mingodad** [comment]
I just updated my repository and the tutorial/Gui14 now look like the screenshots from the web.

Thank you again !

**Comment by klugier** [comment]
As the problem was fixed. I am closing the issue.
