### ISSUE TITLE
Use flagSO option  compile CharSet.h error 

### ISSUE THREAD

**Issue by ongbe** [ultimatepp/ultimatepp#3]
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (155): error: use of undeclared identifier 'IsRTL_'; did you mean 'IsRTL'?
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (156): error: use of undeclared identifier 'IsMark_'; did you mean 'IsMark'?
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (163): error: functions that differ only in their return type cannot be overloaded
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (165): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (166): error: call to 'IsUpper' is ambiguous
 (): inline bool  IsUpper(char c)       { return IsUpper((dword)(byte) c); }
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (159): note: candidate function
 (): inline bool IsUpper(int c)         { return IsUpper((dword) c); }
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (166): note: candidate function
 (): inline bool  IsUpper(char c)       { return IsUpper((dword)(byte) c); }
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (167): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (168): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (169): error: call to 'ToLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (170): error: call to 'ToAscii' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (172): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (173): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (174): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (175): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (176): error: call to 'ToLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (177): error: call to 'ToAscii' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (179): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (180): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (181): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (182): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (155): error: use of undeclared identifier 'IsRTL_'; did you mean 'IsRTL'?
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (156): error: use of undeclared identifier 'IsMark_'; did you mean 'IsMark'?
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (163): error: functions that differ only in their return type cannot be overloaded
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (165): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (166): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (167): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (168): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (169): error: call to 'ToLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (170): error: call to 'ToAscii' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (172): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (173): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (174): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (175): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (176): error: call to 'ToLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (177): error: call to 'ToAscii' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (179): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (180): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (181): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (182): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (155): error: use of undeclared identifier 'IsRTL_'; did you mean 'IsRTL'?
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (156): error: use of undeclared identifier 'IsMark_'; did you mean 'IsMark'?
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (163): error: functions that differ only in their return type cannot be overloaded
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (165): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (166): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (167): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (168): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (169): error: call to 'ToLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (170): error: call to 'ToAscii' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (172): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (173): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (174): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (175): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (176): error: call to 'ToLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (177): error: call to 'ToAscii' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (179): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (180): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (181): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (182): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (155): error: use of undeclared identifier 'IsRTL_'; did you mean 'IsRTL'?
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (156): error: use of undeclared identifier 'IsMark_'; did you mean 'IsMark'?
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (163): error: functions that differ only in their return type cannot be overloaded
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (165): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (166): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (167): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (168): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (169): error: call to 'ToLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (170): error: call to 'ToAscii' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (172): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (173): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (174): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (175): error: call to 'ToUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (176): error: call to 'ToLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (177): error: call to 'ToAscii' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (179): error: call to 'IsLetter' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (180): error: call to 'IsUpper' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (181): error: call to 'IsLower' is ambiguous
/home/ongbee/hub/upp/uppsrc/Core/CharSet.h (182): error: call to 'ToUpper' is ambiguous

**Comment by klugier** [comment]
It seems to be on master branch - https://github.com/ultimatepp/ultimatepp/commit/49b14b2cf56e8b29811b9ec768521f84117531af. I am closing ticket...
