### ISSUE TITLE
UppHub crashes TheIDE

### ISSUE THREAD

**Issue by ismail-yilmaz** [ultimatepp/ultimatepp#32]
ide/UppHub.cpp: 69, crashes TheIDE

https://github.com/ultimatepp/ultimatepp/blob/7306e9c3474e0faf369010ecf479f7792c615305/uppsrc/ide/UppHub.cpp#L69

Should be:

```
readme.Enable(list.IsCursor() && !IsNull(list.Get("README")));
```

**Comment by klugier** [comment]
@ismail-yilmaz please verify and close.

**Comment by ismail-yilmaz** [comment]
Done.
