### ISSUE TITLE
UppWeb: Some of the screeshots on the FAQ page are corrupted.

### ISSUE THREAD

**Issue by ismail-yilmaz** [ultimatepp/ultimatepp#34]
@klugier 

This seems to be a corruption. (It is reproducible on Firefox and Chrome)

[FAQ page](https://www.ultimatepp.org/www$uppweb$FAQ$en-us.html)

Screenshot:

![resim](https://user-images.githubusercontent.com/32938453/104839746-2e6ae300-58d4-11eb-958a-a7ae94a6fb71.png)

**Comment by klugier** [comment]
Hello Oblivion

Locally everything works as expected. Mirek push one little change to uppweb some maybe it will help. At least we should be able to regenerate website again during nightly build.

**Comment by ismail-yilmaz** [comment]
@klugier 

Hmm, have you refreshed your browser's cache?  Because I get the same corrupted images also on Gnome Web, and on Android (with both Chrome and Firefox) too.

Then again, I suggest we leave this issue open  for the time being and I'll re-check the page after the site is regenerated .

**Comment by klugier** [comment]
I can confirm that on ultimatepp.org images are corrupted, with local generation everything is fine.

**Comment by klugier** [comment]
Fixed.
