### ISSUE TITLE
Can I use U++ for commercial software?

### ISSUE THREAD

**Issue by ghost** [ultimatepp/ultimatepp#41]
Hi,

I'm working on a software with QT, however, I may make it proprietary and sell it. If I do that, I cannot use QT without buying a license, which now I cannot afford. So, my question is can I use U++ for commercial and proprietary software?

Thanks.

**Comment by ped7g** [comment]
https://www.ultimatepp.org/app$ide$About$en-us.html

U++ is BSD licensed.

> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

+ no liability whatsoever.

So yes, you can use the U++ for commercial software. You should mention it in documentation. No fees required, no source of your SW required. (BSD is very permissive license, almost "do whatever you want")

**Comment by ped7g** [comment]
but keep an eye on 3rd party libraries you include to be also either BSD/MIT licensed, or at least LGPL and then you have to link dynamically IIRC...

Most of the ecosystem around U++ is BSD/MIT/similar licensed, so generally you don't need to worry about using various other libs and packages form UppHub, except adding those extra mentions/licenses in your documentation (I guess some stuff like zlib is being used almost inevitably if you do any GUI app with U++).

You should be rather aware of all licenses across your project and make sure you fulfil them, especially if you don't plan to publish the source code of your app, then you have to avoid GPL stuff, and use LGPL stuff properly. (but as I wrote, most of the stuff around U++ is BSD/MIT/similar, just be aware of licenses as you add plugins/3rd party libs)

**Comment by mirek-fidler** [comment]
Absolutely.

**Comment by mirek-fidler** [comment]
With respect to 3rd party licenses, note that there is a function
"File/Project licenses" that lists licenses of all modules (packages) that
are used at that moment.

**Comment by ghost** [comment]
Thank you. It's clear now.
