### ISSUE TITLE
Compile for macos/osx 10.14 Mojave

### ISSUE THREAD

**Issue by harrysch** [ultimatepp/ultimatepp#47]
Hi, i tried to compile the source for osx 10.14 - during compilation is an error message about openssl .  
I installed with brew openssl@3 - do i need a different version?

**Comment by klugier** [comment]
Hello,

Please try to install different version. If it doesn't help - then we should modify our initial build method. I spoke with this with Mirek in the past. Please let me know if this works for you - https://www.ultimatepp.org/forums/index.php?t=msg&th=11359&goto=56087&#msg_56087.

Does TheIDE works for you? Could you launch prebuilded TheIDE?

Klugier

**Comment by harrysch** [comment]
Hello,

if i'm searching in the folder ./ultimatepp-master> `find . -name "*bm" -print`

there are   
`./uppbox/Scripts/CLANGMK.bm`  
`./uppbox/Scripts/GCCMK.bm`

no CLANG.bm

i modified INC/LIB to

```
INCLUDE = "/usr/include;/usr/local/opt/openssl/include";
LIB = "/usr/lib;/usr/local/opt/openssl/lib";
```

after new configure and make still shows

```
In file included from ./uppsrc/Core/SSL/SSL.icpp:1:
./uppsrc/Core/SSL/SSL.h:3:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
```

with 

```
find  /usr/local/opt/openssl/include   -name ssl.h  -print
```

there is a

```
/usr/local/opt/openssl/include/openssl/ssl.h
```

adding INCLUDE and LIB to the Makefile does also won't help

btw. there is maybe more missing, running make shows (with or without INC/LIB)

```
Package xinerama was not found in the pkg-config search path.
Perhaps you should add the directory containing `xinerama.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xinerama' found
Package xft was not found in the pkg-config search path.
Perhaps you should add the directory containing `xft.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xft' found
Package libnotify was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnotify.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libnotify' found
In file included from ./uppsrc/Core/SSL/SSL.icpp:1:
In file included from ./uppsrc/Core/SSL/SSL.h:1:
In file included from ./uppsrc/Core/Core.h:306:
```

**Comment by klugier** [comment]
Hello @harrysch,

The compilation on macOS has been fix. Please try again and let us know if it works as expected.

Klugier
