### ISSUE TITLE
forum problem

### ISSUE THREAD

**Issue by austin2209** [ultimatepp/ultimatepp#48]
Hello,
I created an account on the forum the other day and wrote my first topic in the newbie section. My new topic didn't post, i thought maybe it needed manual approval, but after days my topic was never posted. The odd thing is, after i tried to login i found out that my account was deleted since i couldn't login nor my email was recognized when i tried to rest my password.
Is the forum dead or did i do something wrong to trigger some antispam mechanism?
Thank you.

**Comment by klugier** [comment]
Hello Austing,

I must deleted your account. I would like to sorry for that. Could you recall your message? I usually delete messages that are one liners for or the message adds nothing to the discussion, but only for the new users (without approved message). The forum is alive and it is main communication channel for U++.

Please recreate your account and post initial post on our forum. Once the initial post will be approved the account will not be deleted in the future. We have spam filter only on the first message. It must be accepted by the administrator/moderator. Please past your forum login here, so I will be aware about you.

If you are in similar situation to austin2209 please let me know in this thread. On the other hand we need to protect our forum from spam. So, situation like this might happened. If you refer directly to U++ in your first message or you post question - your account should be approved.

At the end I would like to thank you for your interest in our product.

Klugier

**Comment by austin2209** [comment]
My post wasn't that short, I even made an image to make my question clear, but I'll recreate an account.
Thank you for the clarification and for this awesome Framework.

**Comment by klugier** [comment]
Then I am waiting for your account and old/new post :)
