### ISSUE TITLE
How To Compile Source?

### ISSUE THREAD

**Issue by ejamshidiasl** [ultimatepp/ultimatepp#5]
Hello
i want to compile source in windows 10.
i have visual studio 2017
how to do this?

and U++ is fantastic,thank you

**Comment by mirek-fidler** [comment]
Easiest path is to download U++

https://www.ultimatepp.org/www$uppweb$download$en-us.html

start theide, choose the project (e.g. example) and press Ctrl+F5...

Mirek

**Comment by ejamshidiasl** [comment]
yes i did it before.but now i like to build from source.is there any tutorials?
and one other question.is it possible to reduce output file size?it is too big for small app

**Comment by mirek-fidler** [comment]
This is building from source....

To reduce output size, compile as Release and with MSC. However, minimal
size will about 2MB.

**Comment by ejamshidiasl** [comment]
cool and thank you.now output size is really nice.and speed of startup and runtime is best
and how about build source?!?!?if it is opensource so where is build document?

**Comment by mirek-fidler** [comment]
That it. All sources all open at all times. What you did is "building from
sources" (in our context).

If you want to rebuild theide, just select 'uppsrc'/'ide'.

U++ is using its own build system. theide (or umk) is equivalent of 'make'.
We have 'export makefile' function, but that is just for building theide or
umk for the first time.

Mirek
