### ISSUE TITLE
Does upp support IME for unicode language?

### ISSUE THREAD

**Issue by AllenDang** [ultimatepp/ultimatepp#50]
I noticed that input box doesn't support to enter Chinese characters with IME. Does this be supported by upp?

**Comment by mirek-fidler** [comment]
It would be good to specify the platform you are using (Win? Gtk? Mac?)..

That said, so far we only tried for basic support - one of reasons is that
there are not many developers that have IME native language. And nobody
really complained so far.

I would be glad to improve IME support as long as I have some feedback on
what the support is supposed to be. I mean, if somebody can lead me to
understand how to actually use IME (in non-U++ application, say Notepad in
win32), I am pretty sure I can duplicate the experience in U++ :)

**Comment by AllenDang** [comment]
@mirek-fidler I'm using macOS 12.0.1. I'm evaluating ultimate++ for next project, it has most beautiful C++ usage compare to wxWidget and Qt, the only thing blocks me is IME support now.

**Comment by mirek-fidler** [comment]
Frankly, MacOS is the least matured version as of now (OTOH, it will not
mature unless it is used ;)

Could you perhaps check how satisfied are you with IME in Windows or Linux?
I mean, from what I understand, there are like 2 levels of IME - "in place
IME" and "it gets done somewhere on the screen, then put to the
application". So far we have tried to support the second one in both
Windows and Linux (it is easier).

Mirek

**Comment by AllenDang** [comment]
@mirek-fidler I don't have a Windows or Linux by my side. And the next project of my company is aiming to ship a cross-platform GUI toolkit mainly for macOS and should be able to support Windows and Linux.

The second IME support should be enough for me.

**Comment by mirek-fidler** [comment]
Pity...

Anyway, if you could direct me to some description on how I could test IME
on MacOS, I might try to fix that ASAP.

Mirek

**Comment by AllenDang** [comment]
Here is a link provided by apple to guide you installing chinese IME, maybe this will help?
https://support.apple.com/guide/chinese-input-method/set-up-the-input-source-cim6023ab944/mac

**Comment by AllenDang** [comment]
@mirek-fidler Any progress?

**Comment by mirek-fidler** [comment]
No progress yet, sorry. But it is definitely planned before next release,
which should be in 2-3 months.

**Comment by mirek-fidler** [comment]
Sorry for the longer delay than anticipated, on the bright side I managed to implement more "proper" support for input method on all supported platforms. Merged now, please test.

https://www.ultimatepp.org/forums/index.php?t=msg&th=11770&start=0&
