### ISSUE TITLE
Add Ultimate++ release info into readme

### ISSUE THREAD

**Issue by githubgit** [ultimatepp/ultimatepp#6]
I spent couple of hours to find that at least build 11873 of Ultimate++ is required to build this amazing C++ port of ConvNetJS. 

Would you mind to add Ultimate++ release info to readme please.
So others will spent less time looking for correct environment for building.

All Ultimate++ releases could be found here:
https://sourceforge.net/projects/upp/files/upp/

Thanks a lot for your work

**Comment by klugier** [comment]
@githubgit - what do you mean by release info?
