### ISSUE TITLE
ImageOp.cpp ->  FlipImage

### ISSUE THREAD

**Issue by lcineyes** [ultimatepp/ultimatepp#66]
Sorry, My English is very poor.

//ImageOp.cpp ->  FlipImage
Image FlipImage(const Image& m, int mode)
{
	return decode(mode,
	              FLIP_MIRROR_HORZ, MirrorHorz(m),
	              FLIP_ROTATE_180, Rotate180(m),
	              FLIP_MIRROR_VERT, MirrorVert(m),
	              FLIP_TRANSPOSE, Transpose(m),
	              FLIP_ROTATE_CLOCKWISE, RotateClockwise(m),
	              FLIP_TRANSVERSE, Transverse(m),
	              FLIP_ROTATE_ANTICLOCKWISE, RotateAntiClockwise(m),
	              m);
}

//Fh.h
template <class T, class V>
constexpr const V& decode(const T& sel, const V& def)
{
	return def;
}

template <class T, class K, class V, typename... L>
constexpr V decode(const T& sel, const K& k, const V& v, const L& ...args)
{
	return sel == k ? v : (V)decode(sel, args...);
}

In the FlipImage funciton, each conversion function is executed once before the mode hit.

**Comment by kov-serg** [comment]
Yes of course. To [RotateAntiClockwise](https://github.com/ultimatepp/ultimatepp/blob/master/uppsrc/Draw/ImageOp.cpp#L748) it calls all previous transformations and trash them.
I wounder why not to use simple switch instead this crutches?
