### ISSUE TITLE
SetCurrentDirectory() fails with "ñ" in Windows 10

### ISSUE THREAD

**Issue by izabala123** [ultimatepp/ultimatepp#67]
It seems to work using ToSystemCharset(). 
It may be included in U++ implementation of SetCurrentDirectory().
Other functions like GetCurrentDirectory() already include FromSystemCharsetW().

```
// Test case
String folderName = "c:\\Demo ñ";
bool ret;
ret = SetCurrentDirectory(folderName);			// Returns false
ret = SetCurrentDirectory(ToSystemCharset(folderName));	// Returns true
````

**Comment by mirek-fidler** [comment]
I cannot use SetCurrentDirectory here as that is Win32 API function (which years ago I have created trivial implementation for POSIX).

I have added ChangeCurrentDirectory....

**Comment by izabala123** [comment]
I understand. It is right. 
However, for compatibility please make the ChangeCurrentDirectory() accessible on both Windows and Linux, being this function the one we would document in U++.
