### ISSUE TITLE
Bug in drag and drop

### ISSUE THREAD

**Issue by kov-serg** [ultimatepp/ultimatepp#69]
https://github.com/ultimatepp/ultimatepp/blob/master/uppsrc/Core/Defs.h#L157
```
typedef uint32             wchar;
```
https://github.com/ultimatepp/ultimatepp/blob/master/uppsrc/CtrlCore/CtrlClip.cpp#L118
```
String Unicode__(const WString& w)
{
	return String((const char *)~w, 2 * w.GetLength());
}
```
wchar is 4 bytes long so string will hold only one first characted.

How to reproduce. Create textedit type some text, select several letters and move it with mouse. It moves only first letter, rest will disappear.

ps: 
https://github.com/ultimatepp/ultimatepp/blob/master/uppsrc/plugin/lz4/lib/lz4.c#L1348
```
static size_t LZ4_stream_t_alignment(void)
{
    struct { char c; LZ4_stream_t t; } t_a;
    return sizeof(t_a) - sizeof(t_a.t);
}
```
should be replaced with
```
static size_t LZ4_stream_t_alignment(void)
{
    struct { char c; int* t; } t_a;
    return sizeof(t_a) - sizeof(t_a.t);
}
```
in order to work with gcc, or it fall's on aligment check [nearby](https://github.com/ultimatepp/ultimatepp/blob/master/uppsrc/plugin/lz4/lib/lz4.c#L1361)  an cause segav

**Comment by mirek-fidler** [comment]
Should be now fixed (by removing Unicode__ functions completely). Thanks
for spotting this.

pá 8. 4. 2022 v 23:07 odesílatel kov-serg ***@***.***> napsal:

**Comment by kov-serg** [comment]
Did you check result?

![pic-02](https://user-images.githubusercontent.com/5946122/163034566-088fb7bd-45e0-4c1f-865f-f2765c155713.png)
![pic-03](https://user-images.githubusercontent.com/5946122/163034571-d2404339-a1f7-4d90-aef9-77a16a88976e.png)

From wordpad text inserted without problem using drag and drop. But in reverse direction it paste trash. And from textedit itself paste trash. Problem is in inserting data into clip buffer. It insets it in utf8.

ps: I found. This [line](https://github.com/ultimatepp/ultimatepp/blob/master/uppsrc/CtrlCore/Win32Clip.cpp#L282)
```
return String(h.begin(), sizeof(char16) * h.GetCount());
```
should looks like this:
```
return String((char*)h.begin(), sizeof(char16) * h.GetCount());
```
