### ISSUE TITLE
VirtualGui calls undeclared Unicode__()

### ISSUE THREAD

**Issue by izabala123** [ultimatepp/ultimatepp#71]
In Windows 10, when compiling uppweb, VirtualGui/Clip.cpp fails because Unicode__() is not declared.

In revision 2db6c3dfd  declarations and definitions where removed.
In that revision, previous calls to Unicode__() where replaced in other locations. For example, in Win32Clip.cpp:

```
 static String sWText(const Value& data)
 {
-	return Unicode__(WString(data));
+	Vector<char16> h = ToUtf16(WString(data));
+	return String(h.begin(), sizeof(char16) * h.GetCount());
 }
```

Maybe something equivalent could be applied to VirtualGui.

Best regards
Iñaki

**Comment by mirek-fidler** [comment]
Thanks, hopefully fixed.

**Comment by izabala123** [comment]
Excellent. Thank you!
