### ISSUE TITLE
error: no member named 'SetFont' in 'MyCtrl' in GUI Tutorial Gui21

### ISSUE THREAD

**Issue by erusyd** [ultimatepp/ultimatepp#74]
In GUI Tutorial Gui21, when I right click to add "User class", the default **widget properties** are as follows:

![image](https://user-images.githubusercontent.com/1529102/166895724-c86e34f7-4cbd-4f73-ad65-ea2d2d2346e1.png)

If I set "SetFont()" and "SetInk()" in **Gui21.lay** like this:
```
LAYOUT(Gui21Layout, 200, 100)
	ITEM(MyCtrl, myctrl, SetFont(StdFont(11)).SetInk(Black).LeftPosZ(44, 112).VSizePosZ(32, 32))
END_LAYOUT
```
It compiles with error:
```
error: no member named 'SetFont' in 'MyCtrl'
```
I have to remove "SetFont()" and "SetInk()" in **Gui21.lay** to get it compiled.
So what are they for of these widget properties?

**Comment by mirek-fidler** [comment]
Well, it is sort of gray area, these are leftover from normal widgets, the idea being that either your widget knows them or you leave them unused.

Should I try to remove them?

**Comment by erusyd** [comment]
OK. Maybe the gray area is not prominent. I think we can simply remove them or set them read-only if we can't use them. They are misleading as these properties are editable.

**Comment by mirek-fidler** [comment]
Done.
