### ISSUE TITLE
Improvement on widgets properties of layer designer

### ISSUE THREAD

**Issue by erusyd** [ultimatepp/ultimatepp#75]
Maybe we can improve on the following case when the text is long:
![image](https://user-images.githubusercontent.com/1529102/167758927-efe7410d-7ae0-4735-86b3-6389c8b4c962.png)

The part marked in red rectangular can not be stretched.

**Comment by mirek-fidler** [comment]
I have tried to fix this, please check with master.

**Comment by erusyd** [comment]
Thank you. BTW, is there any suggested multimedia development kit for U++ (like QtAV for QT)?

**Comment by mirek-fidler** [comment]
Not at the moment. Would be a nice addition to upphub...

pá 13. 5. 2022 v 4:14 odesílatel Song Yadong ***@***.***>
napsal:
