### ISSUE TITLE
clang-c/Index.h doesn't exist

### ISSUE THREAD

**Issue by izabala123** [ultimatepp/ultimatepp#95]
ide/clang/clang.h includes <clang-c/Index.h>, but this file doesn't exist.

**Comment by klugier** [comment]
Hello Inaki, please download latest nightly build ([upp-win-16332.7z](https://www.ultimatepp.org/downloads/upp-win-16332.7z) should be fine). It should contain needed header. It is located under bin/llvm. After that you need to modify your build method to include this file. The same is true for the lib - you need libclang.lib from bin/llvm. I hope this help.

**Comment by klugier** [comment]
It should be automatically detect uopn setup (https://github.com/ultimatepp/ultimatepp/blob/e8035690b984f06c1d3794b6ef6b4dcd2e0505b4/uppsrc/ide/InstantSetup.cpp#L202), so I assume that there is no issue at the moment. Please very.

**Comment by izabala123** [comment]
Thank you Klugier. Anyway I prefer to wait a little bit to have the GitHub sources updated. I also wanted to point out that this problem does not only happen with CLANG, but also with MSVC 2017.

**Comment by mirek-fidler** [comment]
If you want "clean fix without reinstalling theide", I am afraid you will
need to download llvm and get those headers and libraries there. At this
point I am not even sure this will work (I mean if theide can be compiled)
with msvc and frankly I do not care.

Once the "use libclang" path was chosen, some options are now closed.

**Comment by izabala123** [comment]
Now I understand. clang includes and library are now included in U++ .zip. Once changed actual TheIDE setup options, new TheIDE compiles perfectly with CLANG. Knowing that MSVC is not supported for TheIDE, I have removed it from my personal unittest. Thank you.
